In [23]:
import sys
sys.path.append('..')
import warnings
if not sys.warnoptions:
    warnings.simplefilter("ignore")
import numpy as np
np.warnings.filterwarnings('ignore')
import matplotlib
from matplotlib import pyplot as plt
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import time
from titration import *
from bindingmodels import *
import tensorflow as tf
tf.enable_eager_execution()
import tensorflow_probability as tfp
tfd = tfp.distributions

In [25]:
print([tf.zeros(10), tf.ones(10)])

[<tf.Tensor: id=117, shape=(10,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>, <tf.Tensor: id=119, shape=(10,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>]


In [30]:
data = np.random.normal(np.zeros(10), np.ones(10))
data = tf.constant(data, dtype=tf.float32)


def joint_log_prob(loc, scale, data=data):
    rv = tfd.Normal(loc=loc, scale=scale)
    return rv.log_prob(data)

chain = tfp.mcmc.sample_chain(
        num_results=int(10e3),
        num_burnin_steps=int(1e3),
        current_state=[tf.zeros(10), tf.ones(10)],
        kernel=tfp.mcmc.TransformedTransitionKernel(
            inner_kernel=tfp.mcmc.HamiltonianMonteCarlo(
                target_log_prob_fn=joint_log_prob,
                num_leapfrog_steps=2,
                step_size=tf.Variable(1.),
                step_size_update_fn=tfp.mcmc.make_simple_step_size_update_policy()),
            bijector=[tfp.bijectors.Exp(), tfp.bijectors.Exp()]))





In [31]:
print(chain)



[[<tf.Tensor: id=9131396, shape=(10000, 10), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: id=9131397, shape=(10000, 10), dtype=float32, numpy=
array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)>], TransformedTransitionKernelResults(transformed_state=[<tf.Tensor: id=9131398, shape=(10000, 10), dtype=float32, numpy=
array([[-inf, -inf, -inf, ..., -inf, -inf, -inf],
       [-inf, -inf, -inf, ..., -inf, -inf, -inf],
       [-inf, -inf, -inf, ..., -inf, -inf, -inf],
       ...,
       [-inf, -inf, -inf, ..., -inf, -inf, -inf],
       [-inf, -inf, 