In [1]:
import sys
sys.path.append('..')
from titration import *
import warnings
if not sys.warnoptions:
    warnings.simplefilter("ignore")
import matplotlib
from matplotlib import pyplot as plt
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import time

## Preparation
Let's get a protein stock and a ligand stock, as well as two empty cell.
The first one is a analytical one.
The second one, we don't use any analytical method.


In [2]:
protein_stock = Solution(conc_p=0.01, d_conc_p=1e-3)
ligand_stock = Solution(conc_l=0.1, d_conc_l=1e-3)

In [3]:
well0 = SingleWell()
well1 = SingleWell(analytical = False)


In [4]:
for dummy_idx in range(10):
    well1.inject(protein_stock, 1, 1e-2)


In [5]:
vols, concs_p, concs_l, concs_r = well1.sample(100)

[[0.         0.01025786 0.01113037 ... 0.01044742 0.01039299 0.01028378]
 [0.         0.01104432 0.01090764 ... 0.01098517 0.01068415 0.01078213]
 [0.         0.00963525 0.00975278 ... 0.01047096 0.01042565 0.01040441]
 ...
 [0.         0.01117896 0.01015316 ... 0.01026509 0.01034282 0.01028801]
 [0.         0.00936331 0.00990538 ... 0.01029579 0.01034027 0.01037554]
 [0.         0.00888454 0.00934351 ... 0.00982872 0.00983512 0.00987592]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.07774875e-04 1.06568771e-04 8.06653206e-05
  7.691513

In [6]:
np.average(vols, axis=0).flatten()

array([ 0.        ,  0.99936323,  2.00034713,  3.00028825,  4.0008168 ,
        5.00208248,  6.00299687,  7.00433875,  8.00494087,  9.00544879,
       10.00365615])

## Test 0: The correlation between volumes and concentrations, with only protein.

Take a look at the distance between our calculated cov matrix and the real one.

In [7]:
concs_p_dists = []
vols_dists = []
for n_titration in range(50):
    
    well0 = SingleWell()
    well1 = SingleWell(analytical = False)
    for dummy_idx in range(n_titration):
        well0.inject(protein_stock, 1, 1e-2)
        well1.inject(protein_stock, 1, 1e-2)
    
    well0_vols_cov = well0.vols_cov
    well0_concs_p_cov = well0.concs_cov[0, :]
    vols, concs_p, concs_l, concs_r = well1.sample(10000)
    well1_vols_cov = np.cov(vols.transpose())
    well1_concs_p_cov = np.cov(concs_p.transpose())
    concs_p_dists.append(np.linalg.norm(well0_concs_p_cov - well1_concs_p_cov))
    vols_dists.append(np.linalg.norm(well0_vols_cov - well1_vols_cov))


[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
0.0
[0. 0. 0.]
(10000, 1)
[[0.         0.00815372]
 [0.         0.0115078 ]
 [0.         0.01018364]
 ...
 [0.         0.00911232]
 [0.         0.00958873]
 [0.         0.0090236 ]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.         0.        ]
 [0.         0.00010027]]
[[[0.00000000e+00]
  [0.00000000e+00]]

 [[0.00000000e+00]
  [1.01327626e-06]]

 [[0.00000000e+00]
  [0.00000000e+00]]

 [[0.00000000e+00]
  [0.00000000e+00]]

 [[0.00000000e+00]
  [0.00000000e+00]]

 [[0.00000000e+00]
  [0.00000000e+00]]]
(10000, 2)
[[0.         0.0106737  0.009436  ]
 [0.         0.00952084 0.00929607]
 [0.         0.00922701 0.00942858]
 ...
 [0.         0.00979911 0.01066319]
 [0.         0.00906637 0.01032795]
 [0.         0.00945389 0.01025521]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0.

[[0.         0.01063395 0.01112794 ... 0.01027194 0.01015064 0.0102017 ]
 [0.         0.01112638 0.01100774 ... 0.00975714 0.00988677 0.00964684]
 [0.         0.00978566 0.00974185 ... 0.00997083 0.0097543  0.00957587]
 ...
 [0.         0.01028629 0.01094377 ... 0.01010409 0.01017593 0.01002596]
 [0.         0.00903081 0.00970301 ... 0.00984035 0.00954811 0.00971509]
 [0.         0.00893062 0.00939909 ... 0.00975622 0.00975396 0.01015261]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 9.95935144e-05 1.01393778e-04 1.02166689e-04
  1.02253847e-04 1.02571746e-04 1.02940297e-04 1.02367507

[[0.         0.01048332 0.01062458 ... 0.01007249 0.01016019 0.01029798]
 [0.         0.00899241 0.00918974 ... 0.00987201 0.00983205 0.00982802]
 [0.         0.01014647 0.01023866 ... 0.01016658 0.01017521 0.01002468]
 ...
 [0.         0.00887816 0.00930805 ... 0.00986657 0.00999025 0.01000663]
 [0.         0.01047966 0.01040194 ... 0.01041293 0.01031842 0.0103697 ]
 [0.         0.00900824 0.0087692  ... 0.00988694 0.00996907 0.00995733]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 9.97877859e-05 9.98120140e-05 9.75848521e-05
  9.720663

[[0.         0.0122344  0.01133084 ... 0.00992805 0.00997224 0.00993347]
 [0.         0.00912921 0.01118624 ... 0.01075622 0.0107163  0.01065271]
 [0.         0.00887414 0.00898335 ... 0.00973785 0.00979038 0.00971322]
 ...
 [0.         0.00964682 0.00930157 ... 0.00971066 0.00979129 0.00987882]
 [0.         0.00996342 0.01063249 ... 0.01024529 0.01015727 0.01015166]
 [0.         0.01064185 0.00943522 ... 0.00949589 0.0094887  0.0094502 ]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 9.78937969e-05 9.571474

[[0.         0.00904593 0.00987702 ... 0.00966294 0.00980427 0.00985529]
 [0.         0.00906885 0.00943867 ... 0.00969741 0.00961495 0.00965888]
 [0.         0.01058004 0.01120886 ... 0.00987094 0.00981175 0.00976399]
 ...
 [0.         0.01114878 0.01040015 ... 0.01008375 0.01014084 0.01009944]
 [0.         0.00995528 0.01013949 ... 0.0096202  0.00971146 0.00961065]
 [0.         0.01034069 0.00996237 ... 0.01022756 0.01010026 0.01011978]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.000000

[[0.         0.01138394 0.01021586 ... 0.00988588 0.00981671 0.00991705]
 [0.         0.0117735  0.01063914 ... 0.00996153 0.00998285 0.00993774]
 [0.         0.00977704 0.01014913 ... 0.01037781 0.01032478 0.01035612]
 ...
 [0.         0.00950195 0.01042049 ... 0.01020366 0.01020957 0.0101877 ]
 [0.         0.0092752  0.00989488 ... 0.00997916 0.01003369 0.00990321]
 [0.         0.00968732 0.00947012 ... 0.00990229 0.00984238 0.0098103 ]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00305855e-04 9.99466961e-05 1.00583690e-04
  1.01042807e-04 1.01609463e-04 1.01943981e-04 1.02101966e-04
  1.01246740e-04 9.96468126e-05 1.00090868e-04 1.00162632e-04
  1.00497931e-04 9.97200694e-05 1.00288242e-04 1.00260167e-04
  9.98369658e-05 9.98692793e-05]
 [0.00000000e+00 9.99466961e-05 2.02045295e-04 2.02986178e-04
  2.03250552e-04 2.03621083e-04 2.04125013e-04 2.04268698e-04
  

[[0.         0.00847883 0.00958588 ... 0.01015525 0.0101165  0.01008905]
 [0.         0.01171813 0.01085917 ... 0.01027423 0.01024272 0.01023707]
 [0.         0.00980891 0.00898471 ... 0.00967762 0.00952038 0.00960238]
 ...
 [0.         0.00972545 0.01001145 ... 0.00965641 0.00963751 0.00970187]
 [0.         0.01091097 0.01123743 ... 0.0099824  0.00999854 0.00993843]
 [0.         0.01048921 0.01022435 ... 0.01001186 0.01010368 0.01012865]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.00010165 0.00010266 0.00010476 0.00010665 0.000107
  0.00010622 0.00010539 0.00010623 0.00010684 0.00010697 0.00010848
  0.00010804 0.00010717 0.00010674 0.00010629 0.00010447 0.00010517
  0.00010531 0.0001052  0.00010392 0.00010266]
 [0.         0.00010266 0.0002052  0.00020816 0.00020999 0.00021
  0.00020977 0.00020836 0.00020847 0.00020991 0.0002106  0.00021101
  0.00021026 0.00020928 0.00020891 0.00020875 0.00020721 0.00020675
  0.00020608 0.00020741 0.00020479 0.00020398]
 [0.         0.00010476 0.00020816 0.00031222 0.00031365 0.00031324
  0.00031412 0.00031179 0.00031148 0.00031101 0.00031239 0.00031204
  0.00031134 0.00030986 0.00030973 0.00030836 0.0003054  0.00030304
  0.00030267 0.00030242 0.00029881 0.00029985]
 [0.         0.00010665 0

[[0.         0.00910405 0.00891031 ... 0.0100346  0.01005577 0.01002231]
 [0.         0.00841311 0.0098564  ... 0.01001625 0.00998943 0.0099641 ]
 [0.         0.00926942 0.01001201 ... 0.00996519 0.00995369 0.00998108]
 ...
 [0.         0.00791603 0.00929991 ... 0.01009547 0.01018207 0.01022902]
 [0.         0.00856228 0.00899263 ... 0.00965821 0.00964966 0.00966313]
 [0.         0.01034635 0.00947297 ... 0.01012177 0.01008865 0.01012005]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e

[[0.         0.01001512 0.0102453  ... 0.00993115 0.00991969 0.00994978]
 [0.         0.00965402 0.0092054  ... 0.00993894 0.00996253 0.0099673 ]
 [0.         0.01055256 0.01070548 ... 0.00996353 0.01001002 0.01000343]
 ...
 [0.         0.00955496 0.00986316 ... 0.00997603 0.01002064 0.01009426]
 [0.         0.00962404 0.01016277 ... 0.01012822 0.01010863 0.0100832 ]
 [0.         0.00772028 0.00910582 ... 0.01046461 0.01046061 0.01039937]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e

(10000, 27)
[[0.         0.00933    0.01007908 ... 0.01003153 0.01004051 0.00997021]
 [0.         0.00941137 0.00958653 ... 0.01004317 0.01004633 0.01012004]
 [0.         0.0097683  0.0102916  ... 0.00980616 0.00985886 0.00981891]
 ...
 [0.         0.01015225 0.01094264 ... 0.01052698 0.0104771  0.0104424 ]
 [0.         0.00829277 0.00881882 ... 0.00955433 0.00959229 0.00956659]
 [0.         0.00927993 0.00966    ... 0.01003395 0.010041   0.01000304]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00

[[0.         0.01024169 0.00970049 ... 0.00998952 0.00993972 0.00992042]
 [0.         0.00890735 0.00980259 ... 0.0098377  0.00982358 0.00983491]
 [0.         0.00950159 0.00986261 ... 0.00977859 0.00980778 0.00982854]
 ...
 [0.         0.00963041 0.00904209 ... 0.00981702 0.00983654 0.00979588]
 [0.         0.01116528 0.01107522 ... 0.01010127 0.01012552 0.0101289 ]
 [0.         0.01016676 0.01015894 ... 0.01002432 0.01007563 0.01009636]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.

[[[0.00000000e+00]
  [0.00000000e+00]
  [0.00000000e+00]
  ...
  [0.00000000e+00]
  [0.00000000e+00]
  [0.00000000e+00]]

 [[0.00000000e+00]
  [9.86422347e-07]
  [4.95547114e-07]
  ...
  [3.93080451e-08]
  [3.79200152e-08]
  [3.69508973e-08]]

 [[0.00000000e+00]
  [4.95547114e-07]
  [4.98789759e-07]
  ...
  [3.77803940e-08]
  [3.64311914e-08]
  [3.54968859e-08]]

 ...

 [[0.00000000e+00]
  [0.00000000e+00]
  [0.00000000e+00]
  ...
  [0.00000000e+00]
  [0.00000000e+00]
  [0.00000000e+00]]

 [[0.00000000e+00]
  [0.00000000e+00]
  [0.00000000e+00]
  ...
  [0.00000000e+00]
  [0.00000000e+00]
  [0.00000000e+00]]

 [[0.00000000e+00]
  [0.00000000e+00]
  [0.00000000e+00]
  ...
  [0.00000000e+00]
  [0.00000000e+00]
  [0.00000000e+00]]]
(10000, 30)
[[0.         0.01027603 0.01003272 ... 0.00985211 0.00986735 0.00985133]
 [0.         0.01033797 0.00891112 ... 0.00971167 0.00973779 0.00975413]
 [0.         0.01032381 0.01019606 ... 0.01013446 0.01014467 0.0101488 ]
 ...
 [0.         0.01102322 0.

[[0.         0.0089116  0.00919054 ... 0.01037734 0.01039071 0.01041434]
 [0.         0.01083774 0.01015908 ... 0.00986378 0.00981808 0.0098188 ]
 [0.         0.01068773 0.00996691 ... 0.00971346 0.00972553 0.00971487]
 ...
 [0.         0.00979829 0.01032266 ... 0.00984457 0.00984242 0.00981793]
 [0.         0.00919666 0.0096065  ... 0.0100733  0.01004829 0.01009662]
 [0.         0.01097535 0.01086115 ... 0.00968515 0.00969287 0.00972703]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 9.94800833e-05 9.97142807e-05 ... 1.06696222e-04
  1.06546729e-04 1.07596971e-04]
 [0.00000000e+00 9.97142807e-05 2.01286262e-04

[[0.         0.01146325 0.01061127 ... 0.00994702 0.00994299 0.00990983]
 [0.         0.00967539 0.01032923 ... 0.00995198 0.00999676 0.00999797]
 [0.         0.01032653 0.01178652 ... 0.01027209 0.01022332 0.01020246]
 ...
 [0.         0.00855814 0.00984784 ... 0.01001319 0.0100475  0.01006335]
 [0.         0.01173074 0.01107626 ... 0.01010939 0.01008354 0.01005837]
 [0.         0.00857883 0.0095048  ... 0.00992289 0.00990935 0.00994573]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.01906103e-04 1.02845639e-04 ... 1.01063235e-04
  1.00348209e-04 9.94274647e-05]
 [0.00000000e+00 1.02845639e-04 2.05658296e-04

[[0.         0.01107286 0.01037021 ... 0.00985019 0.00985984 0.00985092]
 [0.         0.01097676 0.01055865 ... 0.01013134 0.01011282 0.01011407]
 [0.         0.00998231 0.01000632 ... 0.00977356 0.00979485 0.00981991]
 ...
 [0.         0.00930461 0.00995956 ... 0.00993395 0.00996669 0.00993823]
 [0.         0.01039684 0.01085635 ... 0.00998581 0.01002539 0.01003954]
 [0.         0.01044026 0.0106423  ... 0.01007643 0.01004358 0.00998831]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 9.82748809e-05 9.89074435e-05 ... 1.07357530e-04
  1.06177082e-04 1.07989064e-04]
 [0.00000000e+00 9.89074435e-05 2.01586736e-04

[[0.         0.00672826 0.00855459 ... 0.00989553 0.0098957  0.00988332]
 [0.         0.01021219 0.00992544 ... 0.00976683 0.00976103 0.00974714]
 [0.         0.01020747 0.01009456 ... 0.01010366 0.01009514 0.01009921]
 ...
 [0.         0.01073054 0.00992301 ... 0.01015384 0.01010699 0.01012497]
 [0.         0.0114748  0.01007463 ... 0.00987689 0.00989901 0.00988846]
 [0.         0.01097559 0.01049727 ... 0.00976951 0.00978611 0.00984299]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 9.77905756e-05 9.83611109e-05 ... 1.00360210e-04
  1.01875608e-04 1.02611398e-04]
 [0.00000000e+00 9.83611109e-05 1.99597961e-04

[[0.         0.01088173 0.01088378 ... 0.01002746 0.00998513 0.00998533]
 [0.         0.01119723 0.01112156 ... 0.00994417 0.00996714 0.0099859 ]
 [0.         0.01001535 0.01033073 ... 0.00979694 0.00976809 0.00977547]
 ...
 [0.         0.00968035 0.00985641 ... 0.00994209 0.0099511  0.00991994]
 [0.         0.00998809 0.00971469 ... 0.00987538 0.00985912 0.00989541]
 [0.         0.01041289 0.01084694 ... 0.00983207 0.00983625 0.00985948]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00557724e-04 9.93551216e-05 ... 1.04648819e-04
  1.03874686e-04 1.03225954e-04]
 [0.00000000e+00 9.93551216e-05 1.97233994e-04

In [ ]:
plt.clf()
plt.plot(vols_dists)

## Test 1: See if there is correlation between protein concentration and ligand concentration.

In [ ]:
concs_p_dists = []
vols_dists = []
for n_titration in range(50):
    
    well0 = SingleWell()
    well1 = SingleWell(analytical = False)
    for dummy_idx in range(n_titration):
        well0.inject(protein_stock, 1, 1e-2)
        well1.inject(protein_stock, 1, 1e-2)
        
        well0.inject(ligand_stock, 0.5, 0.5 * 1e-2)
        well1.inject(ligand_stock, 0.5, 0.5 * 1e-2)
    

    vols, concs_p, concs_l, concs_r = well1.sample(10000)
    

In [ ]:
np.linalg.norm(np.cov(concs_l))